Select * from Salesman
--1.Write a SQL query to find all the orders issued by the salesman 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id
SELECT * FROM Orders
WHERE salesman_id =
    (SELECT salesman_id FROM salesman 
     WHERE Salesman_Name='Paul Adam');

 --2.write a SQL query to find all the orders, which are generated by those salespeople, who live in the city of London.Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
SELECT * FROM Orders
WHERE salesman_id IN
    (SELECT salesman_id 
     FROM salesman 
     WHERE city='London');

--3.write a SQL query to find the orders generated by the salespeople who works for customers whose id is 3007. Return ord_no, purch_amt, ord_date, customer_id, salesman_id. A customer can works only with a salespeople
SELECT *FROM Orders
WHERE salesman_id =
    (SELECT DISTINCT salesman_id 
     FROM orders 
     WHERE customer_id =3007);

--4.write a SQL query to find the order values greater than the average order value of 10th October 2012. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
SELECT * FROM Orders
WHERE purch_amt >
    (SELECT  AVG(purch_amt) 
     FROM Orders 
     WHERE order_date ='10/10/2012');

--5.write a SQL query to find all the orders generated in New York city. Return ord_no, purch_amt, ord_date, customer_id and salesman_id
SELECT *FROM orders
WHERE salesman_id IN
    (SELECT salesman_id 
     FROM salesman 
     WHERE city ='New York');

--6.write a SQL query to find the salespeople who had more than one customer. Return salesman_id and name
SELECT salesman_id,Salesman_Name
FROM salesman a
WHERE 1 < 
    (SELECT COUNT(*) 
     FROM customer 
     WHERE salesman_id=a.salesman_id);

--7.write a SQL query to find those orders, which are higher than average amount of the orders. Return ord_no, purch_amt, ord_date, customer_id and salesman_id
SELECT * FROM orders a
WHERE purch_amt >
    (SELECT AVG(purch_amt) FROM orders b 
     WHERE b.customer_id = a.customer_id);

 --8.Write a query to find the sums of the amounts from the orders table, grouped by date, eliminating all those dates where the sum was not at least 1000.00 above the maximum order amount for that date
  SELECT Order_Date, SUM (purch_amt)
FROM orders a
GROUP BY Order_Date
HAVING SUM (purch_amt) >
    (SELECT 1000.00 + MAX(purch_amt) 
     FROM orders b 
     WHERE a.Order_Date = b.Order_Date);

--9.Write a query to extract all data from the customer table if and only if one or more of the customers in the customer table are located in London.
SELECT customer_id,Customer_Name, city
FROM Customer
WHERE EXISTS
   (SELECT *
    FROM customer 
    WHERE city='London');

-- 10.write a SQL query to find the salespeople who deal multiple customers. Return salesman_id, name, city and commission
SELECT * 
FROM salesman 
WHERE salesman_id IN (
   SELECT DISTINCT salesman_id 
   FROM customer a 
   WHERE EXISTS (
      SELECT * 
      FROM customer b 
      WHERE b.salesman_id=a.salesman_id 
      AND b.Customer_Name<>a.Customer_Name));